Add many smarty blocks
PrestaShop/StarterTheme pull request #167
Opened 2017-01-18 13:41 UTC by julienbourdeau

2017-01-18 16:42 UTC, maximebiloe requested changes

2017-01-18 16:42 UTC, maximebiloe commented on templates/checkout/_partials/cart-detailed.tpl
> +{block name='cart_detailed_product_line'}
block name already define inside the tpl included line 6

2017-01-20 14:33 UTC, martinfojtik commented on templates/customer/_partials/login-form.tpl
> +  {block name='login_form'}
there is `{block name='login_form'}` inside `{block name='login_form'}`

2017-01-23 14:11 UTC, martinfojtik commented on templates/checkout/_partials/cart-detailed-product-line.tpl
> +  <span class="product-price">{$product.total}</span>
@julienbourdeau  can you replace `{$product.total}` with this:
```
{if isset($product.is_gift) && $product.is_gift}
<span class="gift">{l s='Gift' d='Shop.Theme.Checkout'}</span>
{else}
{$product.total}
{/if}
```

2017-01-25 10:51 UTC, julienbourdeau commented on templates/customer/_partials/login-form.tpl
> +  {block name='login_form'}
Thanks! I'll fix it

2017-01-25 13:56 UTC, julienbourdeau commented on templates/checkout/_partials/cart-detailed-product-line.tpl
> +  <span class="product-price">{$product.total}</span>
You're right! Thanks!

2017-02-10 12:49 UTC, maximebiloe approved these changes

2017-02-10 12:53 UTC, maximebiloe commented
Thank you @julienbourdeau

2017-02-10 12:53 UTC, merged